name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 rapidfuzz pyperclip

      - name: Build executable (Linux)
        run: |
          pyinstaller mc_replacer.py --noconfirm --icon=MineCraft.ico --onefile --name mc-replacer-linux

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: mc-replacer-linux
          path: dist/mc-replacer-linux

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 rapidfuzz pyperclip

      - name: Build executable (Windows)
        run: |
          pyinstaller mc_replacer.py --noconfirm --icon=MineCraft.ico --onefile --name mc-replacer-win.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: mc-replacer-win
          path: dist/mc-replacer-win.exe
