name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pyinstaller customtkinter pyperclip

      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole Custom.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: mc-replacer-windows
          path: dist/replacer.exe
